# Generated by Django 4.2.1 on 2023-06-04 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llm_webgate', '0004_alter_anwser_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anwser',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='anwser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='llm_webgate.anwser'),
        ),
    ]
